### ISSUE TITLE
[SUGGESTION]

### ISSUE THREAD

**Issue by cI0ak** [gitrous/origins#61]
Maybe decorate the graves of fallen cops by adding a badge or something to it? Just to show some honor to the people who gave their life to protect ours.

**Comment by gitrous** [comment]
Yes, if a cop gets CKed we will put a flag or something at his grave. The thing is, we don’t CK cops very much because we don’t have any. The only dead cop in Origins is Fedorov, and he has a whole memorial separate from the graveyard. Also, please name your thread something more related, I can’t tell what’s what when I just see “suggestion”
